language: php

php:
    - 7.2

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

sudo: false
dist: trusty

services:

before_script:
    - composer self-update --2
    - composer install

script:
    - composer test
