language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

sudo: false
dist: trusty

services:

before_script:
    - composer self-update --2
    - composer --version
    - composer install

script:
    - composer test
